// build.rs — Assembles the AP trampoline into raw bytes.
//
// The trampoline must be at physical address 0x8000 at runtime, but the
// kernel is linked at 0x40000000. Including the 16-bit trampoline via
// global_asm! causes linker relocations that overflow 16-bit bounds.
//
// Solution: assemble the trampoline separately, extract raw bytes, and
// emit them as a Rust static array.

use std::process::Command;
use std::env;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("trampoline_bytes.rs");

    // Source file
    let src_path = PathBuf::from("src/arch/x86_64/ap_trampoline.S");

    if !src_path.exists() {
        // No trampoline source — emit empty stub
        std::fs::write(&out_path, "pub static AP_TRAMPOLINE: [u8; 0] = [];\n").unwrap();
        return;
    }

    // Assemble with GNU assembler
    let obj_path = Path::new(&out_dir).join("ap_trampoline.o");
    let bin_path = Path::new(&out_dir).join("ap_trampoline.bin");

    let status = Command::new("as")
        .args(&["--32", "-o", obj_path.to_str().unwrap(), src_path.to_str().unwrap()])
        .status()
        .expect("Failed to run 'as' — is GNU assembler installed?");

    if !status.success() {
        panic!("Failed to assemble ap_trampoline.S");
    }

    // Link to flat binary at 0x8000
    let ld_script = format!(
        "SECTIONS {{ . = 0x8000; .text : {{ *(.text) }} .data : {{ *(.data) }} }}\n"
    );
    let ld_path = Path::new(&out_dir).join("trampoline.ld");
    std::fs::write(&ld_path, &ld_script).unwrap();

    let status = Command::new("ld")
        .args(&[
            "-m", "elf_i386",
            "-T", ld_path.to_str().unwrap(),
            "--oformat", "binary",
            "-o", bin_path.to_str().unwrap(),
            obj_path.to_str().unwrap(),
        ])
        .status()
        .expect("Failed to run 'ld'");

    if !status.success() {
        panic!("Failed to link trampoline");
    }

    // Read the flat binary and emit as Rust bytes
    let bytes = std::fs::read(&bin_path).expect("Failed to read trampoline binary");
    let len = bytes.len();

    let mut code = format!("// Auto-generated by build.rs — AP trampoline blob ({} bytes)\n", len);
    code.push_str(&format!("pub static AP_TRAMPOLINE: [u8; {}] = [\n", len));
    for (i, byte) in bytes.iter().enumerate() {
        if i % 16 == 0 {
            code.push_str("    ");
        }
        code.push_str(&format!("0x{:02X}, ", byte));
        if i % 16 == 15 {
            code.push('\n');
        }
    }
    code.push_str("];\n");

    std::fs::write(&out_path, &code).unwrap();
    println!("cargo:rerun-if-changed=src/arch/x86_64/ap_trampoline.S");
}
