[build]
# Let's default to ARM64 for now since that's where our UART driver is!
target = "aarch64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "relocation-model=static",
    "-C", "link-arg=-no-pie",
]
# Added the isa-debug-exit device at the end!
runner = "qemu-system-x86_64 -nographic  -no-reboot -device isa-debug-exit,iobase=0xf4,iosize=0x04 -kernel"

[target.armv7a-none-eabi]
rustflags = [
    "-C", "link-arg=-Tlink.ld",
]

[target.aarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tlink.ld",
]
# Added runner for aarch64 to boot our virt machine
runner = "qemu-system-aarch64 -machine virt -m 1024 -cpu cortex-a53 -nographic -kernel"